version: '3'
services:

  postgres-fastapi:
    build: 
        context: .
        dockerfile: dockerization/Dockerfile-db
  
  nginx:
    image: nginx:latest
    volumes:
        - ./services/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:80"

  fastapi-app:
    build:
      context: .
      dockerfile: dockerization/Dockerfile-api
    volumes:
      - ./src:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8080:8080"
    depends_on:
      - postgres-fastapi
      - nginx
    restart: on-failure
